### ISSUE TITLE
Extract Native Image from Docker Image

### ISSUE THREAD

**Issue by uzshrestha** [paketo-buildpacks/java-native-image#106]
## What happened?

I am trying to extract the image (exec) that native buildpack created and want to run it outside docker. I tried this
```
mvn spring-boot:build-image
docker run --rm -it -e SPRING_PROFILES_ACTIVE=hsqldb -p 9090:8080 -v "$(pwd)/target/workspace":/workspace petclinic-jpa:0.0.1-SNAPSHOT
```
But got error
```
$ docker run --rm -it -e SPRING_PROFILES_ACTIVE=hsqldb -p 9090:8080 -v "$(pwd)/target/workspace":/workspace petclinic-jpa:0.0.1-SNAPSHOT
ERROR: failed to launch: path lookup: exec: "/workspace/org.springframework.samples.petclinic.PetClinicApplication": stat /workspace/org.springframework.samples.petclinic.PetClinicApplication: no such file or directory
```
Is it possible to do this. 

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by dmikusa** [comment]
I think what's happening is this:

1. You're building your image, that is working
2. It places the native-image binary under `/workspace/org.springframework.samples.petclinic.PetClinicApplication`
3. You volume mount your local folder overtop of `/workspace`
4. The container tries to launch your application when you `docker run` the image, but there is nothing there because you mounted your local volume overtop of the location where the image exists.

You can try some of the options here for copying files out of the container, https://www.baeldung.com/ops/docker-copying-files. Just keep in mind that you can't volume mount over `/workspace` or other folder that exist in the container.

As this is not really an issue with the buildpack, I'm going to close this out. If you have more questions on this topic, I would suggest asking on https://stackoverflow.com/questions/tagged/paketo.
